### ISSUE TITLE
Error while doing a patch in control plane

### ISSUE THREAD

**Issue by paucampana** [siderolabs/pulumi-provider-talos#16]
Hello, 

I am trying to remove `"/cluster/apiServer/admissionControl/"` from the control plane configuration using patches. As it is a field that is only present in control planes (and not in workers), while using the `talosctl` command I needed to use the flag `--config-patch-control-plane`

So, 
- If I run `talosctl gen config talos-k8s-aws-tutorial https://tast:6443/ --with-examples=false --with-docs=false --kubernetes-version 1.23.9  --config-patch-control-plane '[{"op": "remove", "path": "/cluster/apiServer/admissionControl"}]'` it works
- If I run `talosctl gen config talos-k8s-aws-tutorial https://tast:6443/ --with-examples=false --with-docs=false --kubernetes-version 1.23.9  --config-patch '[{"op": "remove", "path": "/cluster/apiServer/admissionControl"}]'
` I am getting the following error:
```
failed to generate config bundle: error patching configs: failure applying rfc6902 patches to talos machine config: remove operation does not apply: doc is missing path: "/cluster/apiServer/admissionControl": missing value
```

So I would like to be available to do the same using the terraform provider, but it looks that I am having a similar error as the previous one:
```
talos_machine_configuration_controlplane.machineconfig_cp: Creating...
╷
│ Error: failure applying rfc6902 patches to talos machine config: remove operation does not apply: doc is missing path: "/cluster/apiServer/admissionControl": missing value
│
│   with talos_machine_configuration_controlplane.machineconfig_cp,
│   on talos-config.tf line 4, in resource "talos_machine_configuration_controlplane" "machineconfig_cp":
│    4: resource "talos_machine_configuration_controlplane" "machineconfig_cp" {
```

My terraform code:
```
resource "talos_machine_configuration_controlplane" "machineconfig_cp" {
  cluster_name     = "test"
  cluster_endpoint = "https://example-lb:443"
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
  config_patches = [
    file("${path.module}/talos-patches/admissioncontroller.yaml")
  ]
  docs_enabled = false
  examples_enabled = false
  kubernetes_version = "1.23.9"
  talos_version = "v1.2.1"

}
```

`talos-patches/admissioncontroller.yaml` file content:
```
[
    {
        "op": "remove",
        "path": "/cluster/apiServer/admissionControl"
    }
]
```

It is a bug or I am doing something wrong?

More context:
https://taloscommunity.slack.com/archives/CG25RPZNE/p1663105063165239

**Comment by frezbo** [comment]
you should be passing in the patches for the `talos_machine_configuration_apply` for the cp nodes.

**Comment by frezbo** [comment]
closing since this should have been in the tf provider repo
